### ISSUE TITLE
Create a STAC catalog for fiboa data

### ISSUE THREAD

**Issue by m-mohr** [fiboa/data#10]
and register on STAC Index.

Could potentially be generated automatically from the Source fiboa organization?

**Comment by cholmes** [comment]
What's the status on this @m-mohr? 

I see STAC catalogs for the datasets you made, which is awesome. Do we just need a higher level catalog to reference each of them?

**Comment by m-mohr** [comment]
Yeah, I wasn't sure how to proceed.

(1) Where to host with a static URL? Source is hard to maintain with regular updates (login, find repo, create AWS credentials, convert credentials to Windows, set up environment, update files locally, upload). And it feels weird to have a Source repo with a single catalog.json in it.

(2) Updating the catalog manually is not ideal, but it looks like there is also no (Source Coop) API that we could generate it from.

Maybe we can maintain on https://github.com/fiboa/fiboa.github.io for now. Let me give it a show.

**Comment by m-mohr** [comment]
https://stacindex.org/catalogs/fiboa#/
https://radiantearth.github.io/stac-browser/#/external/fiboa.org/stac/catalog.json

**Comment by m-mohr** [comment]
I'm also using the STAC catalog now to fill the data repository so that we don't need to maintain things twice:
https://github.com/fiboa/data

**Comment by cholmes** [comment]
Nice! Love it. So to add a new one it's just a PR to https://github.com/fiboa/fiboa.github.io/blob/main/stac/catalog.json ? 

We could also just put the collections there instead of on source? I agree with your assessment that source is annoying to get things on. And that source should be improved so it just generates the STAC. I made a similar suggestion awhile ago - like just have a form to update the common fields, and then just display those in the STAC and in the 'description', instead of having every readme have to fill it out custom.

**Comment by m-mohr** [comment]
Yes, if it has a STAC Collection, see also: https://github.com/fiboa/data?tab=readme-ov-file#add-your-dataset

> We could also just put the collections there instead of on source?

The Collections get created/updated through the CLI with each run, so they should probably be on Source, otherwise it gets annoying to update things in two places.

> I made a similar suggestion awhile ago

Yeah, me too ;-) But just a text editor for (text) files hosted there would also already be a huge improvement ;-)
